### PR TITLE
Add Gitlab support to Docker::Registry

### PR DESCRIPTION
**Pull request by waterkip**
Gitlab does not support the full implemenation of the Docker JWT
registry specs. So not everything can be supported [1].
What is supported is access to single repositories.

[1] https://gitlab.com/gitlab-org/gitlab-ce/issues/47497

### CODE REVIEW

**Comment by pplu** [comment]
Hey! This looks nice! Please tell me when you think it's ready or if you need some help in some place.

One suggestion: if you can put in a Makefile a destination such as `run-gitlab` that runs a container with gitlab to try the authentication it would be awesome.

**Comment by waterkip** [comment]
I'm ready, gitlab is not.. 

Instead of adding something to the Makefile for gitlab, I've added a test in t/400-gitlab-auth.t to prove the authentication works: GITLAB_USERNAME=foo GITLAB_USERNAME=bar prove -lv t/400-gitlab-auth.t

You can also set GITLAB_JWT=https://foo.bar.nl if you want to test against a different JWT server

I've also added something to your dist.ini so I could install the module from within Docker by copying the Makefile.PL from dzil build to the repo.

**Comment by waterkip** [comment]
Gitlab calls the password the personal access token. You cannot login to the registry (or the Gitlab API) with your user credentials. You need to create a personal access token for these actions. Each token can have specific rights (or scopes), eg. read user information, read registry info, etc.

The token itself is the bearer token. It should be a private accessor.. I'll update this.

**Comment by pplu** [comment]
Can we call the password attribute `personal_access_token` or `access_token`?

Please don't make the token attribute private (as the user of the library may have retrieved the bearer token with their own logic). Maybe renaming the token attribute to `bearer_token` be more clarifying.

What do you think?

**Comment by waterkip** [comment]
You have read my mind! I'm in the process of changing password to access_token and token to bearer_token.

**Comment by waterkip** [comment]
I saw you put a skip('foo', 1) in your branch. What version of Test::More are you using?

**Comment by waterkip** [comment]
Fixed it. I cherry-picked your changes as well. Thanks for catching that, It didn't show on my box.

**Pull request merged**
